describe('Editando brinquedo', () => {
    it('Editando brinquedo com sucesso', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_brinquedos/"] > .card').click()
        cy.get('.adicionar').click()
        cy.get('#textFormBrinquedoNome').type('Fantoche ')
        cy.get('#textFormBrinquedoCategoria').type('Fantoche de mão')
        cy.get('#textFormBrinquedoMateriais').type('pano,botões,garrafa pet')
        cy.get('#textFormBrinquedoTematica').type('Fantasia')
        cy.get('#numberFormBrinquedoQuantidade').type('50')
        cy.get('.button').click()
        cy.get('.acoes > a').click()
        cy.get('#textFormBrinquedoNome').clear()
        cy.get('#textFormBrinquedoNome').type('Fantoche Harry Potter')
        cy.get('.button').click()
        
    })

    it('Esquecendo de editar o nome do fantoche', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_brinquedos/"] > .card').click()
        cy.get('.adicionar').click()
        cy.get('#textFormBrinquedoNome').type('Fantoche ')
        cy.get('#textFormBrinquedoCategoria').type('Fantoche de mão')
        cy.get('#textFormBrinquedoMateriais').type('pano,botões,garrafa pet')
        cy.get('#textFormBrinquedoTematica').type('Fantasia')
        cy.get('#numberFormBrinquedoQuantidade').type('50')
        cy.get('.button').click()
        cy.get('.acoes > a').click()
        cy.get('#textFormBrinquedoNome').clear()
        cy.get('.button').click()
    })

    it('Editando a quantidade de brinquedos', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_brinquedos/"] > .card').click()
        cy.get('.adicionar').click()
        cy.get('#textFormBrinquedoNome').type('Fantoche ')
        cy.get('#textFormBrinquedoCategoria').type('Fantoche de mão')
        cy.get('#textFormBrinquedoMateriais').type('pano,botões,garrafa pet')
        cy.get('#textFormBrinquedoTematica').type('Fantasia')
        cy.get('#numberFormBrinquedoQuantidade').type('50')
        cy.get('.button').click()
        cy.get('.acoes > a').click()
        cy.get('#numberFormBrinquedoQuantidade').clear()
        cy.get('#numberFormBrinquedoQuantidade').type('20')
        cy.get('.button').click()

    })
})