describe('Filtrando colaboradoras', () => {
    it('Filtrar colaboradora por skills com sucesso', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click()
        cy.get('.novo-cadastro-card').click()
        cy.get('#textFormNome').type('Andressa')
        cy.wait(2000)
        cy.get('#numberFormIdade').type(30)
        cy.get('#numberFormCpf').type(65390182170)
        cy.get('#numberFormCelular').type(81994350921)
        cy.get('#textFormEmail').type('andressa@gmail.com')
        cy.get('#numberFormCep').type(51089472)
        cy.get('#textFormCidade').type('Recife')
        cy.get('#textFormBairro').type('Boa Viagem')
        cy.get('#textFormRua').type('Rua conde')
        cy.get('#numberFormNumero').type(456)
        cy.get('#textFormComplemento').type('bloco 1 apt 201')
        cy.get('#textFormEscolaridade').type('Ensino médio completo')
        cy.get('#textFormExperiencia').type('nunca trabalhei')
        cy.get('#textFormDisponibilidade').type('tempo integral')
        cy.get('#textFormInteresse').type('não tenho')
        cy.get('[for="selectSkillCostura"]').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('.mensagem').invoke('text').should('have.string', "Cadastro adicionado com sucesso!")
        cy.wait(2000)
        cy.get('[href="/aplicacao/gerenciar_skills/"] > h1').click()
        cy.wait(2000)
        cy.get('select').select('Costura')
        cy.wait(2000)
        cy.get('button').click()
        cy.get('.cadastro-card').invoke('text').should('have.string', "Andressa")
        cy.wait(5000)
    })

    it('Filtrando colaboradora por skills de Pintura', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click()
        cy.get('.novo-cadastro-card').click()
        cy.get('#textFormNome').type('Andressa')
        cy.wait(2000)
        cy.get('#numberFormIdade').type(30)
        cy.get('#numberFormCpf').type(65390182170)
        cy.get('#numberFormCelular').type(81994350921)
        cy.get('#textFormEmail').type('andressa@gmail.com')
        cy.get('#numberFormCep').type(51089472)
        cy.get('#textFormCidade').type('Recife')
        cy.get('#textFormBairro').type('Boa Viagem')
        cy.get('#textFormRua').type('Rua conde')
        cy.get('#numberFormNumero').type(456)
        cy.get('#textFormComplemento').type('bloco 1 apt 201')
        cy.get('#textFormEscolaridade').type('Ensino médio completo')
        cy.get('#textFormExperiencia').type('nunca trabalhei')
        cy.get('#textFormDisponibilidade').type('tempo integral')
        cy.get('#textFormInteresse').type('não tenho')
        cy.get('[for="selectSkillPintura"]').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('.mensagem').invoke('text').should('have.string', "Cadastro adicionado com sucesso!")
        cy.wait(2000)
        cy.get('[href="/aplicacao/gerenciar_skills/"] > h1').click()
        cy.wait(2000)
        cy.get('select').select('Pintura')
        cy.get('button').click()
        cy.get('.cadastro-card').invoke('text').should('have.string', "Andressa")
        cy.wait(5000)
    })

    it('Filtrando skills sem ter nenhuma colaboradora com ela', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click()
        cy.wait(2000)
        cy.get('[href="/aplicacao/gerenciar_skills/"] > h1').click()
        cy.get('select').select('Gerenciamento')
        cy.wait(2000)
        cy.get('button').click()
        cy.get('.lista-de-cadastros > h1').invoke('text').should('have.string', "Nenhum cadastro com essa habilidade!")
    })
})