describe('Visualizando colaboradora', () => {
    it('Visualizando colaboradora com sucesso', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click();
        cy.get('.novo-cadastro-card').click()
        cy.get('#textFormNome').type('Andressa')
        cy.get('#numberFormIdade').type(30)
        cy.get('#numberFormCpf').type(65390182170)
        cy.get('#numberFormCelular').type(81994350921)
        cy.get('#textFormEmail').type('andressa@gmail.com')
        cy.get('#numberFormCep').type(51089472)
        cy.get('#textFormCidade').type('Recife')
        cy.get('#textFormBairro').type('Boa Viagem')
        cy.get('#textFormRua').type('Rua conde')
        cy.get('#numberFormNumero').type(456)
        cy.get('#textFormComplemento').type('bloco 1 apt 201')
        cy.get('#textFormEscolaridade').type('Ensino médio completo')
        cy.get('#textFormExperiencia').type('nunca trabalhei')
        cy.get('#textFormDisponibilidade').type('tempo integral')
        cy.get('#textFormInteresse').type('não tenho')
        cy.get('[for="selectSkillCostura"]').click()
        cy.get('[for="selectSkillPintura"]').click()
        cy.get('.button').click()
        cy.get('.mensagem').invoke('text').should('have.string', "Cadastro adicionado com sucesso!")
        cy.get('.cadastro-card').click()
        cy.get('#cadastro-estilo').invoke('text').should('have.string', "Cadastro de Andressa")
    })

    it('Visualizando colaboradora com dados incompletos', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click();
        cy.get('.novo-cadastro-card').click()
        cy.get('#textFormNome').type('Andressa')
        cy.get('#numberFormIdade').type(30)
        cy.get('#numberFormCpf').type(65390182170)
        cy.get('#numberFormCelular').type('81994350921')
        cy.get('#textFormEmail').type('andressa@gmail.com')
        cy.get('#numberFormCep').type(51089472)
        cy.get('#textFormCidade').type('Recife')
        cy.get('#textFormBairro').type('Boa Viagem')
        cy.get('#textFormRua').type('Rua conde')
        cy.get('#numberFormNumero').type(456)
        cy.get('#textFormEscolaridade').type('Ensino médio completo')
        cy.get('#textFormExperiencia').type('nunca trabalhei')
        cy.get('#textFormDisponibilidade').type('tempo integral')
        cy.get('#textFormInteresse').type('não tenho')
        cy.get('[for="selectSkillCostura"]').click()
        cy.get('[for="selectSkillPintura"]').click()
        cy.get('.button').click()
        cy.get('.mensagem').invoke('text').should('have.string', "Cadastro adicionado com sucesso!")
        cy.get('.cadastro-card').click()
        cy.get('#cadastro-estilo').invoke('text').should('have.string', "Cadastro de Andressa")
        cy.get(':nth-child(13) > :nth-child(2)').invoke('text').should('have.string', "")
    })

    it('Visualizando colaboradora com comentario', () => {
        cy.visit('/delete_cypress/')
        cy.get('.button').click()
        cy.get('[href="/login/"]').click()
        cy.get('p > a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('#password_confirm').type('abc123')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('abc123')
        cy.get('.button').click()
        cy.get('[href="/aplicacao/home_cadastros/"] > .card').click();
        cy.get('.novo-cadastro-card').click()
        cy.get('#textFormNome').type('Andressa')
        cy.get('#numberFormIdade').type(30)
        cy.get('#numberFormCpf').type(65390182170)
        cy.get('#numberFormCelular').type(81994350921)
        cy.get('#textFormEmail').type('andressa@gmail.com')
        cy.get('#numberFormCep').type(51089472)
        cy.get('#textFormCidade').type('Recife')
        cy.get('#textFormBairro').type('Boa Viagem')
        cy.get('#textFormRua').type('Rua conde')
        cy.get('#numberFormNumero').type(456)
        cy.get('#textFormComplemento').type('bloco 1 apt 201')
        cy.get('#textFormEscolaridade').type('Ensino médio completo')
        cy.get('#textFormExperiencia').type('nunca trabalhei')
        cy.get('#textFormDisponibilidade').type('tempo integral')
        cy.get('#textFormInteresse').type('não tenho')
        cy.get('[for="selectSkillCostura"]').click()
        cy.get('[for="selectSkillPintura"]').click()
        cy.get('.button').click()
        cy.get('.mensagem').invoke('text').should('have.string', "Cadastro adicionado com sucesso!")
        cy.get('[href="/aplicacao/adicionar_comentario/"] > h1').click()
        cy.get('select').select('Andressa')
        cy.get('#texto').type('Melhor colaboradora')
        cy.get('button').click()
        cy.get('.cadastro-card').click()
        cy.get('#cadastro-estilo').invoke('text').should('have.string', "Cadastro de Andressa")
        cy.get('li').invoke('text').should('have.string', "Andressa: Melhor colaboradora")
    })
})