# Generated by Django 4.2.14 on 2024-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_cadastros_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastros',
            name='skillCostura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillGerenciamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillPintura',
            field=models.BooleanField(default=False),
        ),
    ]
