# Generated by Django 5.1.1 on 2024-11-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_colaborador_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.AddField(
            model_name='comentario',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.cadastros'),
        ),
    ]
