# Generated by Django 4.2.14 on 2024-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caregoria', models.CharField(max_length=100)),
                ('materiais', models.CharField(max_length=200)),
                ('tematica', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
