# Generated by Django 4.2.14 on 2024-11-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_brinquedo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brinquedo',
            old_name='caregoria',
            new_name='categoria',
        ),
    ]
