# Generated by Django 4.2.14 on 2024-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_rename_caregoria_brinquedo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='materiais',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='tematica',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
