# Generated by Django 4.2.14 on 2024-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_alter_brinquedo_categoria_alter_brinquedo_materiais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='materiais',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='tematica',
            field=models.CharField(max_length=100),
        ),
    ]
