# Generated by Django 4.2.14 on 2024-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0011_alter_brinquedo_categoria_alter_brinquedo_materiais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
