# Generated by Django 4.2.14 on 2024-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0013_brinquedo_usuario_cadastros_usuario_pasta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastros',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
