# Generated by Django 4.2.14 on 2024-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0014_cadastros_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastros',
            name='disponibilidade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='escolaridade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='experiencia',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='interesse',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillAtendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillCriatividade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillDesign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillLimpeza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='skillVendas',
            field=models.BooleanField(default=False),
        ),
    ]
